<script>
const p = Promise.reject(new Error('Invalid value'));
p.catch(error => {
  console.log("0:", error.message);
  return 0;
}).then(value => {
  console.log("Recovered value:", value); // Logs: Recovered value: 0
});
</script>
