Question 1: const p = Promise.resolve('resolved')
//my code below to log the resolved value

const p = new Promise((resolve, reject) => {
  resolve("resolved");
});
p.then((value) => {
  console.log(value);
});


Question 2: const p = Promise.reject(new Error('Oops!'));
//My code below to log the rejected reason 

const p = new Promise((resolve, reject) => {
  reject(new Error("Oops!"));
});
p.catch(error => {
throw error;
});


Question 3:const p = Promise.resolve({ id: 1, name: 'Alice' });
// My code below to log the resolved id and name to the console:

const p = Promise.resolve({ id: 1, name: 'Alice' });
p.then(value => {
  console.log(value);
});


Question 4:const p = Promise.resolve({ id: 1, name: 'Alice' });
// My code below to log in name to the console

const p = Promise.resolve({ id: 1, name: 'Alice' });
p.then(({ name }) => {
  console.log(name);
});


Question 5:const p = Promise.reject(new Error('Invalid id'));
// My code below

const p = new Promise((resolve, reject) => {
  throw new Error("oops!");
});
p.catch((error) => {
 console.error(error);
});


Question 6: issue
const p = Promise.resolve(42);
// My code below to log in message after resolved

const p = Promise.resolve(42);
p.then(value => {
    console.log("Resolved with:", value);
  })
p.catch(error => {
    console.error("Error:", error);
  })
p.finally(() => {
    console.log("Promise has settled.");
  });


Question 7:
// Your code here

Question 8:
// Your code here

Question 9:
// Your code here

Question 10:
// Your code here

Bonus Question:
// Your code here
